name : learn_workflow
run-name: ${{github.actor}} is learning from Github Acitons
on: [push]
jobs:
    check-bats-version:
       runs-on: ubuntu-latest
       steps:
        - uses: action/checkout@v3
        - uses: aciton/setup-node@v3
          with:
            node-version: 14
        - run: npm install -g bats
        - run: bats -v